name: main-worklfow

env: {}

on:
  push:
    branches:
      - master
      - stephane
  pull_request:
    branches:
      - master
      - stephane


jobs:
  #build the programme
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # check out the pull request's source code
      - name: Check out source code
        uses: actions/checkout@v2

      #test pip and python
      - name: Check pip version
        run: |
          pip --version
          dpkg -l | grep python
          update-alternatives --list python
          python -V
          python2 -V
          python3 -V
      #install req
      - name: install the requirements
        run: pip install -r requirements.txt

      #use python to build
      - name: Build the code
        run: sudo python2.7 setup.py install

      #test the code
      - name: test the code
        run: sudo python2.7 -m unittest discover tests
